//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Sfx
    {
        public const string BundleName = "sfx";
        public const string CLICK = "Click";
        public const string SLIDERDOWN = "SliderDown";
        public const string SLIDERUP = "SliderUp";
    }
    public class Uifocusespanel_prefab
    {
        public const string BundleName = "uifocusespanel_prefab";
        public const string UIFOCUSESPANEL = "UIFocusesPanel";
    }
    public class Uiratingpanel_prefab
    {
        public const string BundleName = "uiratingpanel_prefab";
        public const string UIRATINGPANEL = "UIRatingPanel";
    }
    public class Uiresultpanel_prefab
    {
        public const string BundleName = "uiresultpanel_prefab";
        public const string UIRESULTPANEL = "UIResultPanel";
    }
    public class Uistartpanel_prefab
    {
        public const string BundleName = "uistartpanel_prefab";
        public const string UISTARTPANEL = "UIStartPanel";
    }
}
